swagger: '2.0'
info:
  description: |
    API to simplify the life of people sharing room/apartments
    
  version: 1.0.0
  title: Roomates API
  contact:
    email: leonerosario92@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
- name: group
  description: API for group management. A group models a set of person living together

paths:
  /group:
    post:
      tags:
      - group
      summary: Create a new group 
      operationId: createGroup
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Newly defined group
        required: true
        schema:
          $ref: '#/components/schemas/Group'
      responses:
        201:
          description: Created
        400:
          description: Bad Request
        500:
          description: Internal Server Error    

components:
  schemas:
    Group:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
  

host: localhost:8080
basePath: /rmapi/v1
schemes:
 - https
 - http